default: &default
  adapter: mysql2
  username: root
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: taskdb

test:
  <<: *default
  database: taskdb

production:
  <<: *default
  database: taskdb
